### ISSUE TITLE
Only allow the use of one token per participant

### ISSUE THREAD

**Issue by frbl** [roqua/physiqual#69]
In order to only allow the use of one token per participant, the following needs to change:
- Change the `has_many` in `Physiqual::User` to `has_one`
- Add a uniqueness constraint to the database for `physiqual_user_id` in the `physiqual_tokens` table

Furthermore, we need to remove the code where the data from multiple tokens gets merged and where data is retrieved from multiple sensor provider services.

**Comment by frbl** [comment]
How do we deal with incomplete tokens?

My suggestion, allow a person to have multiple tokens IF there is not yet a valid one.

**Comment by emerencia** [comment]
I don't see why we should make an exception for incomplete tokens. Once a user has clicked on a service, we lock them into that service. So if they click "Google Fit", we create an incomplete google fit token. If they can cancel that process and at a later time try to resume it, we'll resuse that same incomplete token (and since they've already chosen for Google Fit, we don't allow them to switch to a different service). When the oauth registration completes successfully, the incomplete token is updated and becomes a complete token.

**Comment by frbl** [comment]
https://github.com/roqua/physiqual/tree/fb-remove-merging

**Comment by emerencia** [comment]
Fixed in #73.
